### ISSUE TITLE
ModuleNotFoundError: No module named 'command_line'

### ISSUE THREAD

**Issue by ColeShelly** [thebradbain/snapception#12]
Traceback (most recent call last):
  File "/usr/local/bin/snapception", line 7, in <module>
    from snapception.command_line import launch
  File "/usr/local/lib/python3.6/dist-packages/snapception/__init__.py", line 1, in <module>
    import command_line
ModuleNotFoundError: No module named 'command_line'

???

**Comment by ravaxis** [comment]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/snapception", line 11, in <module>
    load_entry_point('snapception==1.1.1', 'console_scripts', 'snapception')()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/snapception/__init__.py", line 1, in <module>
    import command_line
ModuleNotFoundError: No module named 'command_line'

I might be fucking up the version or pythonpath

**Comment by an0ndev** [comment]
Looks like this is an issue with Click versioning: mitmproxy needs click 6.2, but the actual program needs click 7.0, which provides command_line.

**Comment by S1700** [comment]
yo any fixes yet

**Comment by an0ndev** [comment]
To resolve the import issue, try `pip3 install click==7.0`.

**Comment by S1700** [comment]
okay thanks

**Comment by nosson-p** [comment]
I fixed it by pip install command_line
