### ISSUE TITLE
Error trying to run

### ISSUE THREAD

**Issue by adambom** [thebradbain/snapception#2]
Can't run the program on Mac OSX 10.9.5 using a fresh install.

```
Traceback (most recent call last):
  File "/usr/local/bin/snapception", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2603, in <module>
    working_set.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 666, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
pkg_resources.DistributionNotFound: click
```

**Comment by lutfidemirci** [comment]
same here

**Comment by electic** [comment]
same here

**Comment by pellejacobs** [comment]
No snapception for the Apple peeps :/

**Comment by thebradbain** [comment]
I actually also have the same issue on my MacBook Air (10.10), though on my iMac (10.9.5) it installs and runs without a hitch.

If any of you find a solution please feel free to notify me.

**Comment by ankushagarwal** [comment]
I am running OSX 10.10 on Yosemite with Python 2.7.8 . I don't see this issue. I manage my python environment using pyenv

**Comment by ryancowan** [comment]
I was having the same issue as above (Macbook Pro running 10.9.5), but was able to get it running with the following:
`sudo pip2.7 install snapception --upgrade`

**Comment by seyhunak** [comment]
same.

**Comment by niclaslovdahl** [comment]
try

```
easy_install --upgrade pip
```

then

```
pip uninstall snapception
```

then

```
pip install snapception
```

This did it for me!
